import time,os,sys


def eindeNL():
    print("Dit was het einde van het Nederlandse deel van heb verhaal ")
    time.sleep(1.5)
    print("")
    print("Al wil je de andere eindens lezen start het verhaal opnieuw en kies een andere keuze ")
    time.sleep(1.5)
    print("")
    print("supper erg bedankt van het lezen van dit verhaal")
    time.sleep(10)
    print("")
    exit()


def huis():
    print("Na anderhalve week was de moeder er")
    time.sleep(1.5)
    print("")
    print("Een half jaar later...")
    time.sleep(1.5)
    print("")
    print("Nu iedereen een beetje de basics van de Nederlandse taal kan ")
    time.sleep(1.5)
    print("")
    print("Nu kunnen Parwana en haar broertje naar school")
    time.sleep(1.5)
    print("")
    print("En haar vader heeft nu een baan")
    time.sleep(1.5)
    print("")
    print("De moeder zorgt voor de kinderen")
    time.sleep(1.5)
    print("")
    print("Ze kregen ook goed nieuws")
    time.sleep(1.5)
    print("")
    print("Er was een huis beschikbaar waar ze kunnen leven")
    time.sleep(1.5)
    print("")
    print("Toen ze voor het eerst in het huis kwamen konden ze het niet gelooven")
    time.sleep(1.5)
    print("")
    print("Het was veel groter dan waar ze vooreen leefden")
    time.sleep(1.5)
    print("")
    print("Na een week konden ze in het huis wonen en ze zouden ook een verblijfsvergunning krijgen")
    print("ze konden ook niet geloven dat alles zo goed is gekomen")
    print("")
    eindeNL()



def nlfamilie():
    print("Nu alles een beetje goed gaat hadden Parwana en haar vader nog een zorge")
    time.sleep(1.5)
    print("")
    print("Haar moeder en haar broertje die hebben ze al een hele tijd niet gezien")
    time.sleep(1.5)
    print("")
    print("Haar vader wist wel dat ze ook zouden vluchten maar hopelijk is alles goed gegaan")
    time.sleep(1.5)
    print("")
    print("Haar vader vroeg aan de mensen die bij het asielzoekerscentrum werken of hun konden weten of ze ook in Nederland zit")
    time.sleep(1.5)
    print("")
    print("Er was een man die hun mischien wel kon helpen")
    time.sleep(1.5)
    print("")
    print("Hij kon alle namen van de andere asielzoekerscentrums op vragen maar dat zou wel even duren")
    time.sleep(1.5)
    print("")
    print("Dat maakt de vader niet uit")
    print("Even later zij da man dat hij haar naam had gevonden het was in een asielzoekerscentrum in Frankrijk")
    time.sleep(1.5)
    print("")
    print("Haar vader was blij en opgelucht")
    time.sleep(1.5)
    print("")
    print("De vader vroeg of ze naar nederland gebracht kon worden")
    time.sleep(1.5)
    print("")
    print("De man andwoorden er ja op maar dat zou wel even duren")
    time.sleep(1.5)
    print("")
    huis()



def nlverblijfplaats():
    print("Toen ze onder weg waren vertelde de man dat het een asielzoekerscentrum is")
    time.sleep(1.5)
    print("")
    print("Dat is een plek waar allemaal gevluchte mensen zijn")
    time.sleep(1.5)
    print("")
    print("Gelukkig was de rit niet ver")
    time.sleep(1.5)
    print("")
    print("Toen ze er waren bedankte de vader de man nog")
    time.sleep(1.5)
    print("")
    print("De man vertelde waar zij zich moesten aanmelden en daarna ging de man weer")
    time.sleep(1.5)
    print("")
    print("nu ze er eemaal waren en hun hadden aangemeld")
    time.sleep(1.5)
    print("")
    print("de kregen de sleutels voor een kamer")
    time.sleep(1.5)
    print("")
    print("het was erg klein maar dat maakten de vader niks uit")
    time.sleep(1.5)
    print("")
    print("hij was blij zolang ze een verblijfplaats hebben")
    time.sleep(1.5)
    print("")
    print("een week later...")
    time.sleep(3)
    print("")
    print("Pwarana heeft nu een paar vrienden gemaakt zij haar vader enkrijgen nu nederlandse les")
    time.sleep(1.5)
    print("")
    print("Als alles goed gaat met de taal leren kan parwana naar school gaan over een tijdje")
    time.sleep(1.5)
    print("")
    nlfamilie()
    


def NL():
    print("Na nog een dag in de gevangenis zitten liet de baas hun naar het vliegveld brengen")
    time.sleep(1.5)
    print("")
    print("Parwana had nog nooit in een vliegtuig gezeten dus het was best wel spannend voor haar")
    time.sleep(1.5)
    print("")
    print("Maar na een paar uurtjes vliegen kwamen ze aan in Nederland")
    time.sleep(1.5)
    print("")
    print("Nu moesten ze een verblijfplaats zoeken")
    time.sleep(1.5)
    print("")
    print("dat was best moeilijk want ze hadden geen vervoer")
    time.sleep(1.5)
    print("")
    print("haar vader vroeg aan een paar mensen maar zij spraken geen Engels")
    time.sleep(1.5)
    print("")
    print("Toen kwame er een man naar hun toe en vroeg wat er aan de hand was")
    time.sleep(1.5)
    print("")
    print("haar vader had verteld hoe ze hier kwamen en dat ze een verblijfplaats wilde")
    time.sleep(1.5)
    print("")
    print("de man wist een plek waar meeredere vluchtelingen waren")
    time.sleep(1.5)
    print("")
    print("de man vertelde dat hij hun daar kon heen kan brengen")
    time.sleep(1.5)
    print("")
    nlverblijfplaats()



def EN2():
    print("De vader heeft toch besloten om in Engeland te blijfen")
    time.sleep(1.5)
    print("")
    print("hij dacht dat het geen zin had om verder te zoeken ")
    time.sleep(1.5)
    print("")
    print("Zijn vrouw en zoon konden overal zijn ")
    time.sleep(1.5)
    print("mischien waren ze wel gepakt door de taliban of mischien welvermoord")
    time.sleep(1.5)
    print("")
    print("Na een paar weken kreeg de vader een baan aangeboden")
    time.sleep(1.5)
    print("")
    print("En parwana kon binnenkort naar school gaan")
    time.sleep(1.5)
    print("")
    print("Het verhaal eindigd hier")
    time.sleep(1.5)
    print("")
    print("als je de andere eindes ook wilt lezen vul dan bij de keuze een ander antwoord in")
    time.sleep(1.5)
    print("")
    print("supper erg bedankt van het lezen van dit verhaal")
    time.sleep(10)
    print("")
    exit()

def verder():
    print("De vader wilt verder zoeken maar hij weet niet hoe")
    time.sleep(1.5)
    print("")
    print("Hij had nog genoeg geld om naar de haven te gaan om vervolgens met de boot mee te gaan")
    time.sleep(1.5)
    print("")
    print("Maar daarna had hij nog vervoer nodig")
    time.sleep(1.5)
    print("")
    print("Mischien konden zij met iemand mee liften")
    time.sleep(1.5)
    print("")
    print("Met geluk vroeg de vader aan een man en zijn vrouw of ze mee mochten")
    time.sleep(1.5)
    print("")
    print("ze antwoorden daar ja op maar ze zouden wel naar het midden van Frankrijk gaan")
    time.sleep(1.5)
    print("")
    print("dat was eigelijk precies waar de vader heen wilden")
    time.sleep(1.5)
    print("")
    print("Na een lange rit van 12 uur waren ze in frankrijk ")
    time.sleep(1.5)
    print("")
    print("De mensen die ze hadden meegenomen hadden ze afgezet bij het asielzoekerscentrum")
    time.sleep(1.5)
    print("")
    print("gelukkig spraken een paar mensen die daar werkten spraken Engels")
    time.sleep(1.5)
    print("")
    print("De vader had zich weer ingeschreven bij het asielzoekerscentrum")
    time.sleep(1.5)
    print("")
    print("Een dag later vroeg hij weer naar zij vrouw of ze eventueel in frankrijk kan zitten")
    time.sleep(1.5)
    print("")
    print("en het duur de weer even voor dat ze het hadden uit gezocht")
    time.sleep(1.5)
    print("")
    print("even later zij de man dat hij goed nieuws had. Zij vrouw zat in een asielzoekerscentrum in het noorden van Frankrijk")
    time.sleep(1.5)
    print("")
    print("de vader was opgelucht en vroeg of zij en zijn zoon hier heen gebracht konden worden")
    time.sleep(1.5)
    print("")
    print("De man zou dat wel kunnen regelen maar het zou wel even duren")
    time.sleep(1.5)
    print("")
    print("Na een paar dagen kwam de moeder aan met haar zoontje")
    time.sleep(1.5)
    print("")
    print("ze leefden nog een klein tijdje in het asielzoekerscentrum")
    time.sleep(1.5)
    print("")
    print("uiteindelijk had de vader een baan")
    time.sleep(1.5)
    print("")
    print("Parwana en haar broertje moesten de taal nog leren als dat goed ging konden ze naar school")
    time.sleep(1.5)
    print("")
    print("De vader kon niet geloven dat alles goed is gekomen")
    time.sleep(1.5)
    print("Hier eindigd het verhaal van Parwana en haar vader als je de andere eindens wilt zal je een andere keuze moeten maken")
    time.sleep(1.5)
    print("")
    print("supper erg bedankt van het lezen van dit verhaal")
    time.sleep(10)
    exit()

def EN():
    print("Na nog een dag in de gevangenis zitten liet de baas hun naar het vliegveld brengen")
    time.sleep(1.5)
    print("")
    print("Parwana had nog nooit in een vliegtuig gezeten dus het was best wel spannend voor haar")
    time.sleep(1.5)
    print("Na een tijdje vliegen kwamen Parwana en haar vader aan in Engeland")
    time.sleep(1.5)
    print("")
    print("Gelukkig kon haar vader goed Engels")
    time.sleep(1.5)
    print("")
    print("Hij kwam 2 politie mannen tegen en had alles uitgelegd aan hun")
    time.sleep(1.5)
    print("")
    print("Hij vroeg waar hun heen konden gaan")
    time.sleep(1.5)
    print("")
    print("De politie kon hun ergens heen bregen")
    time.sleep(1.5)
    print("")
    print("Het was een gebauw speciaal voor vluchtelingen")
    time.sleep(1.5)
    print("")
    print("Het was net nieuw en er was nog plek")
    time.sleep(1.5)
    print("")
    print("Ze moesten zich eerst inschrijven om daar te kunnen verblijfen")
    time.sleep(1.5)
    print("")
    print("Eemaal ingeschreven konden ze hun kamer in")
    time.sleep(1.5)
    print("")
    print("paar dagen later was de vader en Parwana wat gewend geraakt")
    time.sleep(1.5)
    print("")
    print("maar er was nog een probleem dat ws dat ze niet wisten waar haar moeder en broertje waren")
    time.sleep(1.5)
    print("")
    print("de vader vroeg aan de mensen die daar werkten of hun mischien wisten waar zijn vrouw en zoon konden zijn")
    time.sleep(1.5)
    print("")
    print("de zijden dat ze alleen in engeland konden kijken of ze daar mischien was")
    time.sleep(1.5)
    print("")
    print("een dag later had hij slecht nieuws ze hadden haar naam nergens kunnen vinden")
    time.sleep(1.5)
    print("")
    print("Parwana en haar vader wisten niet wat ze moesten doen")
    time.sleep(1.5)
    print("")
    print("mischie mosten ze naar een ander land toe en daar mischien haar moeder zoeken bij ander asielzoekerscentrum ")
    print("")
    time.sleep(3)
    answer = input("De keuze is nu aan jouw of je blijft in engeland en zoek niet verder naar de vader zijn vrouw en zoon of je gaat naar een anderland zoeken")
    print("Vul |Z| in voor verder te zoeken en vul |E| in om in engeland te blijfen ")
    if answer == "Z":
        print("je gaat verder zoeken naar je vrouw")
        verder()
    elif answer == "E":
        print("je blijft in Engeland")
        EN2()

def dekeuze():
    Answer = input("Welk land wil jij dat Parwana en haar vader heen gaan? let op dit antwoord heeft impact op het einde van het verhaal Kies uit: |NL,FR,BE of EN| ")
    print("")
    time.sleep(1.5)
    if Answer == "NL":
        print("goed je hebt Nederland gekozen laten we verder gaan met het verhaal ")
        print("")
        time.sleep(1.5)
        NL()
    elif Answer == "EN":
        print("jij hebt Engeland gekozen laten we verder gaan met het verhaal")
        print("")
        time.sleep(1.5)
        EN()
    else:
        print("vul een geldig antwoord in!!")
        print("")
        dekeuze()


def gevangenis():
    print("De vader was verdrietig omdat alles zo goed ging")
    time.sleep(1.5)
    print("")
    print("en op het laatste moment ging het fout")
    time.sleep(1.5)
    print("")
    print("het enige voordeel was dat ze nu eten kregen en een dag boven hun hoofd hadden")
    time.sleep(1.5)
    print("")
    print("Na dagen in de gevangenis zitten kwam de vader steeds meer in contact met de baas van de gevangenis")
    time.sleep(1.5)
    print("")
    print("Hij sprak ook de zelfde taal als De vader en Parwana")
    time.sleep(1.5)
    print("")
    print("Hij vroeg zich af waarom ze gevlucht waren")
    time.sleep(1.5)
    print("")
    print("haar vader had alles verteld en")
    time.sleep(1.5)
    print("")
    print("De baas zij dat hij medelijden had")
    time.sleep(1.5)
    print("")
    print("hij zij dat hij een vlucht kon regelen naar 3 verschillende landen")
    time.sleep(1.5)
    print("")
    print("De 4 landen waren Nederland, Frankrijk,en Engeland")
    time.sleep(1.5)
    print("")
    print("De vader was hem supper dankbaar maar hij kon geen keuze maken")
    time.sleep(1.5)
    print("")
    dekeuze()


def dereis2():
    print("Parwana en haar vader zaten nu in de vrachtwagen")
    time.sleep(1.5)
    print("")
    print("Eigelijk ging de rit heel soepel")
    time.sleep(1.5)
    print("")
    print("Er werd één keer gechecked bij de grens maar ze hadden niks door")
    time.sleep(1.5)
    print("")
    print("Nu was het aleen nog maar wachten todat ze er waren")
    time.sleep(1.5)
    print("")
    print("Toen ze er eemaal waren gaf de vriend nog wat eten en drinken mee")
    time.sleep(1.5)
    print("")
    print("Nu Parwana en haar vader er waren konden ze op de boot stappen")
    time.sleep(1.5)
    print("")
    print("er zaten te bijna teveel mensen in de boot ")
    time.sleep(1.5)
    print("")
    print("De boot zou naar Turkije gaan en het zou een heel lange rijs worden")
    time.sleep(1.5)
    print("")
    print("Na dagen op de boot zitten waren Parwana en haar vader er")
    time.sleep(1.5)
    print("")
    print("Toen ze aan kwamen stond de politie de boot op te wachten")
    time.sleep(1.5)
    print("")
    print("Ze hadden veel mensen meegenomen waar onder Parwana en haar vader")
    time.sleep(1.5)
    print("")
    gevangenis()
 

def dereis():
    print("Haar vader wist de route waar ze heen moesten ")
    time.sleep(1.5)
    print("")
    print("de locatie was bij de zee")
    time.sleep(1.5)
    print("")
    print("daar zouden ze via het water kunnen vluchten")
    time.sleep(1.5)
    print("maar eerst moesten ze naar Libanon reizen ")
    print("")
    time.sleep(1.5)
    print("dat zou een gevaarlijke en een verre reis worden ")
    print("")
    time.sleep(1.5)
    print("te voet zou te ver zijn")
    print("")
    time.sleep(1.5)
    print("dus moesten ze met een auto")
    print("")
    time.sleep(1.5)
    print("haar vader had een vriend die hun daar heen kon brengen met een vrachtwagen ")
    print("")
    time.sleep(1.5)
    print("ze konden hun zich in de laading van de vrachtwagen verstoppen")
    print("")
    time.sleep(1.5)
    print("")
    dereis2()

def Taliban():
    print("De vader hoorde de vriend een discussie hebben met iemand van de Taliban")
    time.sleep(1.5)
    print("")
    print("Hij bleek iets verkeerd gedaan te hebben maar de vader wist niet wat")
    time.sleep(1.5)
    print("")
    print("De vriend werd neer geschoten in zijn eigen huis")
    time.sleep(1.5)
    print("")
    print("de Taliban checkten het huis nog ze")
    time.sleep(1.5)
    print("")
    print("hij liep recht boven het luik en merkten dat het hol klonk")
    time.sleep(1.5)
    print("")
    print("hij haalden de mat weg en vond het luik ")
    time.sleep(1.5)
    print("")
    print("hij kwam binnen en nam de vader en Parwana mee")
    time.sleep(1.5)
    print("")
    print("Na een lange rit kwamen ze bij een van hun kampen aan ")
    time.sleep(1.5)
    print("")
    print("er waren erg veel mensen van de taliban daar ")
    time.sleep(1.5)
    print("")
    print("een van hun herkende de vader en wist wat hij deed")
    time.sleep(1.5)
    print("")
    print("haar vader werd vermoord")
    time.sleep(1.5)
    print("")
    print("en er was niks wat Parwana kon doen ")
    time.sleep(1.5)
    print("")
    print("Hier eindigd het verhaal met het slechte einde..")
    time.sleep(1.5)
    print("")
    print("als je da andere eindens wilt lezen maak een andere keuze")
    time.sleep(1.5)
    print("")
    print("Wel erg badankt van het lezen van dit verhaal")
    time.sleep(6)
    print("")
    exit()



def onderduiken():
    print("Je hebt gekozen voor onderduiken... ")
    time.sleep(1.5)
    print("")
    print("de plaats waar ze konden onderduiken was niet heel ver")
    time.sleep(1.5)
    print("")
    print("het was een schuilkelder onder een huis")
    time.sleep(1.5)
    print("")
    print("ze konden daar ook eten en drinken krijgen")
    time.sleep(1.5)
    print("")
    print("en het belangrijkste het zou veilig zijn")
    time.sleep(1.5)
    print("")
    print("toen ze er eemaal waren gingen ze de schuilkelder in")
    time.sleep(1.5)
    print("")
    print("het was goed verstopt en erwas best veel ruimpte")
    time.sleep(1.5)
    print("")
    print("hier zouden ze wel een tijdje kunnen schuilen")
    time.sleep(1.5)
    print("")
    print("na een een paar maanden...")
    time.sleep(1.5)
    print("")
    print("De vader en Parwana zaten nog in de schuilkelder")
    time.sleep(1.5)
    print("")
    Taliban()



def keuze2():
    print("Maar mischien zou de reis wel fout gaan dacht de vader")
    time.sleep(1.5)
    print("")
    print("Mischien kan hij onderduiken bij een vriend")
    time.sleep(1.5)
    print("")
    answer = input("Je kan nu de keuze maken om te vluchten of te onderduiken. Kies |V| voor Vluchten en kies | O  |voor onderduiken.  ")
    if answer == "V":
        print("Je hebt voor vluchten gekozen.")
        time.sleep(1.5)
        print("")
        dereis()
    elif answer == "O":
        onderduiken()
    else:
        print("Type een geldig antwoord let op voor hoofdletters!")
        time.sleep(1.5)
        print("")
        keuze2()



def vluchten2():
    print("toen parwana haar spullen had ingepakt ging ze met haar vader uit huis")
    time.sleep(1.5)
    print("")
    print("zonder haar moeder zusje en broertje omdat ze geen tijd meer hadden om langer te wachten")
    time.sleep(1.5)
    print("")
    print("De vader had haar moeder nog wel geinformeerd met een briefje waar ze heen zouden gaan")
    time.sleep(1.5)
    print("")
    print("haar vader wist een veilige plek om heen te gaan")
    time.sleep(1.5)
    print("")
    print("maar de reis zou niet mischien niet veilig zijn dat hing er van af hoe het zou gaan")
    time.sleep(1.5)
    keuze2()



def vluchten():
    print("op een dag was Parwana alleen thuis")
    time.sleep(1.5)
    print("")
    print("haar vader was eerder thuis van werk")
    time.sleep(1.5)
    print("")
    print("hij zij tegen Parwana dat ze snel haar spullen moest pakken")
    time.sleep(1.5)
    print("")
    print("Parwana snapte er niks van maar ze pakten haar spullen toch")
    time.sleep(1.5)
    print("")
    print("De vader van Parwana had een dreigbrief gekregen van de Taliban")
    time.sleep(1.5)
    print("")
    print("omdat haar vader voor internationale bedrijven werkt en dat mocht niet")
    time.sleep(1.5)
    print("")
    print("een paar van haar ooms waren al vermoord door de Taliban")
    time.sleep(1.5)
    print("")
    print("dus haar vader moest wel vluchten")
    time.sleep(1.5)
    print("")
    vluchten2()



def familie():
    print("Parwana is een 12 jarig meisje ze woont momenteel in Afganistan")
    time.sleep(1.5)
    print("")
    print("Parwana woont samen met haar vader, moeder, broertje en zusje")
    time.sleep(1.5)
    print("")
    print("Haar vader werkt voor internationale bedrijven")
    time.sleep(1.5)
    print("")
    print("en haar moeder zorgt voor de kinderen")
    time.sleep(1.5)
    print("")
    vluchten()



def eerstevraag():
    answer = input ("Wil je dit verhaal lezen? |Ja/Nee| ")
    time.sleep(1.5)
    print("")
    if answer == "Ja":
        print("Goed laten we verder gaan")
        time.sleep(1.5)
        print("")
        familie()
    if answer == "Nee":
        time.sleep(1.5)
        print("")
        print("Oke toch bedankt. doeg")
        exit
    else:
        print("Type een geldig antwoord")
        time.sleep(1.5)
        print("")
        eerstevraag()



def beging():
    print("Hallo")
    time.sleep(1.5)
    print("")
    print("Ik ben Jari")
    time.sleep(1.5)
    print("")
    name = input("Wat is jouw naam? ")
    time.sleep(1.5)
    print("")
    print("Hallo " + name + " Ik ga een verhaal vertellen over een meisje die gevlucht is uit haar land")
    time.sleep(1.5)
    print("")
    eerstevraag()




beging()